In [1]:
import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
df = pd.DataFrame(digits.data,columns=digits.feature_names)
df.head(10)

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   
5        0.0        0.0       12.0       10.0        0.0        0.0   
6        0.0        0.0        0.0       12.0       13.0        0.0   
7        0.0        0.0        7.0        8.0       13.0       16.0   
8        0.0        0.0        9.0       14.0        8.0        1.0   
9        0.0        0.0       11.0       12.0        0.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   
5        0.0        0.0        0.0        0.0  ...        4.0        0.0   
6        0.0        0.0        0.0        0.0  ...        8.0        0.0   
7       15.0        1.0        0.0        0.0  ...        0.0        0.0   
8        0.0        0.0        0.0        0.0  ...        8.0        0.0   
9        0.0        0.0        0.0        2.0  ...        4.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   
5        0.0        0.0        9.0       16.0       16.0       10.0   
6        0.0        0.0        1.0        9.0       15.0       11.0   
7        0.0        0.0       13.0        5.0        0.0        0.0   
8        0.0        0.0       11.0       16.0       15.0       11.0   
9        0.0        0.0        9.0       12.0       13.0        3.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  
5        0.0        0.0  
6        3.0        0.0  
7        0.0        0.0  
8        1.0        0.0  
9        0.0        0.0  

[10 rows x 64 columns]

In [3]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
df['target'] = digits.target
df.head(10)

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   
5        0.0        0.0       12.0       10.0        0.0        0.0   
6        0.0        0.0        0.0       12.0       13.0        0.0   
7        0.0        0.0        7.0        8.0       13.0       16.0   
8        0.0        0.0        9.0       14.0        8.0        1.0   
9        0.0        0.0       11.0       12.0        0.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   
5        0.0        0.0        0.0        0.0  ...        0.0        0.0   
6        0.0        0.0        0.0        0.0  ...        0.0        0.0   
7       15.0        1.0        0.0        0.0  ...        0.0        0.0   
8        0.0        0.0        0.0        0.0  ...        0.0        0.0   
9        0.0        0.0        0.0        2.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   
5        0.0        9.0       16.0       16.0       10.0        0.0   
6        0.0        1.0        9.0       15.0       11.0        3.0   
7        0.0       13.0        5.0        0.0        0.0        0.0   
8        0.0       11.0       16.0       15.0       11.0        1.0   
9        0.0        9.0       12.0       13.0        3.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  
5        0.0       5  
6        0.0       6  
7        0.0       7  
8        0.0       8  
9        0.0       9  

[10 rows x 65 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [12]:
from sklearn.svm import SVC
model = SVC(kernel='linear',C=50,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9796296296296296

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(SVC(kernel='linear',C=50,gamma='auto'),digits.data,digits.target,cv=4)

array([0.95777778, 0.94432071, 0.97327394, 0.92873051])

In [15]:
cross_val_score(SVC(kernel='rbf',C=50,gamma='auto'),digits.data,digits.target,cv=4)

array([0.43777778, 0.42538976, 0.45879733, 0.53006682])

In [16]:
cross_val_score(SVC(kernel='linear',C=20,gamma='scale'),digits.data,digits.target,cv=4)

array([0.95777778, 0.94432071, 0.97327394, 0.92873051])

In [17]:
cross_val_score(SVC(kernel='linear',C=20,gamma='auto'),digits.data,digits.target,cv=4)

array([0.95777778, 0.94432071, 0.97327394, 0.92873051])

In [18]:
import numpy as np

In [22]:
kernel = ['rbf','linear']
C = [1,10,20]
avg_scores = {}
for kval in kernel:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel=kval,C=cval,gamma='auto'),digits.data,digits.target,cv=4)
        avg_scores[kval + '_' +str(cval)] = np.average(cv_scores)
        
avg_scores

{'rbf_1': 0.4379683246721109,
 'rbf_10': 0.46300791883197234,
 'rbf_20': 0.46300791883197234,
 'linear_1': 0.95102573620391,
 'linear_10': 0.95102573620391,
 'linear_20': 0.95102573620391}

In [24]:
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(SVC(gamma='auto'),{
    'C' : [1,10,20],
    'kernel' : ['rbf','linear']
},cv=4,return_train_score=False)

gs.fit(digits.data,digits.target)
gs.cv_results_

{'mean_fit_time': array([0.82304865, 0.06616729, 0.79617524, 0.06927812, 0.74399346,
        0.0601595 ]),
 'std_fit_time': array([0.05593331, 0.00724706, 0.00796927, 0.00317545, 0.03665711,
        0.01453325]),
 'mean_score_time': array([0.13094378, 0.02283955, 0.12519592, 0.02859646, 0.12347013,
        0.02070141]),
 'std_score_time': array([0.01035205, 0.00727933, 0.00417273, 0.00302389, 0.0125556 ,
        0.00492083]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [27]:
df = pd.DataFrame(gs.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.823049      0.055933         0.130944        0.010352       1   
1       0.066167      0.007247         0.022840        0.007279       1   
2       0.796175      0.007969         0.125196        0.004173      10   
3       0.069278      0.003175         0.028596        0.003024      10   
4       0.743993      0.036657         0.123470        0.012556      20   
5       0.060160      0.014533         0.020701        0.004921      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.408889   
1       linear   {'C': 1, 'kernel': 'linear'}           0.957778   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.437778   
3       linear  {'C': 10, 'kernel': 'linear'}           0.957778   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.437778   
5       linear  {'C': 20, 'kernel': 'linear'}           0.957778   

   split1_test_score  split2_test_score  split3_test_score  mean_test_score  \
0           0.405345           0.432071           0.505568         0.437968   
1           0.944321           0.973274           0.928731         0.951026   
2           0.425390           0.458797           0.530067         0.463008   
3           0.944321           0.973274           0.928731         0.951026   
4           0.425390           0.458797           0.530067         0.463008   
5           0.944321           0.973274           0.928731         0.951026   

   std_test_score  rank_test_score  
0        0.040356                6  
1        0.016451                1  
2        0.040516                4  
3        0.016451                1  
4        0.040516                4  
5        0.016451                1

In [30]:
gs.best_score_

0.95102573620391

In [31]:
gs.best_params_

{'C': 1, 'kernel': 'linear'}

In [32]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.437968
1       1       linear         0.951026
2      10          rbf         0.463008
3      10       linear         0.951026
4      20          rbf         0.463008
5      20       linear         0.951026

In [33]:
print('chosing best model')

chosing best model


In [39]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [58]:
model_params = {
    'svm': {
        'model' : SVC(gamma='auto'),
        'params' : {
            'C' : [1,10,20],
            'kernel' : ['rbf','linear']
        }
    },
    'random_forest' : {
        'model' : RandomForestClassifier(),
        'params' : {
            'n_estimators' : [1,5,10]
        }
    },
    'logostic_regression' : {
        'model' : LogisticRegression(solver='liblinear',multi_class='auto'),
        'params' : {
            'C' : [1,5,10]
        }
    }
}


In [59]:
scores = []

for model_name,mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(digits.data,digits.target)
    scores.append({
        'model' : model_name,
        'best_score' : clf.best_score_,
        'best_params' : clf.best_params_,
    })

In [60]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                   best_params
0                  svm    0.947697  {'C': 1, 'kernel': 'linear'}
1        random_forest    0.897634          {'n_estimators': 10}
2  logostic_regression    0.922114                      {'C': 1}

In [67]:
model_params = {
    'svm' : {
        'model' : SVC(gamma='auto'),
        'params' : { 
            'kernel' : ['rbf','linear'],
            'C' : [1,5,1,20]
            } 
    },
    'random_forest' : {
        'model' : RandomForestClassifier(),
        'params' : {
            'n_estimators' : [10,20,30],
            'criterion' : ["gini", "entropy"]
        }
    },
    'logistic_regression' : {
        'model' : LogisticRegression(),
        'params' : {
            'C' : [1,5,10]
        }
    },
    'gaussianNB' : {
        'model' : GaussianNB(),
        'params' : {
#             'priors' : None
        }
    },
    'multinomialNB' : {
        'model' : MultinomialNB(),
        'params' : {
#             'fit_prior' : True
        }
        
        }
}

In [68]:
scores = []

for model_name,mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(digits.data,digits.target)
    scores.append({
        'model' : model_name,
        'best_score' : clf.best_score_,
        'best_params' : clf.best_params_,
    })

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [71]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                                best_params
0                  svm    0.947697               {'C': 1, 'kernel': 'linear'}
1        random_forest    0.936575  {'criterion': 'gini', 'n_estimators': 20}
2  logistic_regression    0.913765                                   {'C': 1}
3           gaussianNB    0.806928                                         {}
4        multinomialNB    0.870350                                         {}